/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./components/CustomVuetify/AlertMessage.vue')['default']
    Breadcrumbs: typeof import('./components/FileManager/Breadcrumbs/Breadcrumbs.vue')['default']
    BtnBase: typeof import('./components/Button/BtnBase.vue')['default']
    BtnBaseIcon: typeof import('./components/Button/BtnBaseIcon.vue')['default']
    BtnSwicthView: typeof import('./components/Button/BtnSwicthView.vue')['default']
    CircularLoader: typeof import('./components/Loader/CircularLoader.vue')['default']
    ColumnDateModified: typeof import('./components/FileManager/CustomCellTemplate/ColumnDateModified.vue')['default']
    ColumnGroupActions: typeof import('./components/FileManager/CustomCellTemplate/ColumnGroupActions.vue')['default']
    ColumnLocation: typeof import('./components/FileManager/CustomCellTemplate/ColumnLocation.vue')['default']
    ColumnName: typeof import('./components/FileManager/CustomCellTemplate/ColumnName.vue')['default']
    ColumnOwner: typeof import('./components/FileManager/CustomCellTemplate/ColumnOwner.vue')['default']
    ColumnPermissionFile: typeof import('./components/FileManager/CustomCellTemplate/ColumnPermissionFile.vue')['default']
    ColumnTimeDeleted: typeof import('./components/FileManager/CustomCellTemplate/ColumnTimeDeleted.vue')['default']
    ContentLoader: typeof import('./components/Loader/ContentLoader.vue')['default']
    ContextMenu: typeof import('./components/FileManager/ContextMenu/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./components/FileManager/ContextMenu/ContextMenuItem.vue')['default']
    FileManager: typeof import('./components/FileManager/FileManager.vue')['default']
    FmContextMenu: typeof import('./components/FileManager/ContextMenu/FmContextMenu.vue')['default']
    FmContextMenuItem: typeof import('./components/FileManager/ContextMenu/FmContextMenuItem.vue')['default']
    FmContextMenuItemv2: typeof import('./components/FileManager/ContextMenu/FmContextMenuItemv2.vue')['default']
    FMEmpty: typeof import('./components/FileManager/partial/FMEmpty.vue')['default']
    GridItem: typeof import('./components/FileManager/GridItem/GridItem.vue')['default']
    GridItemHead: typeof import('./components/FileManager/GridItem/GridItemHead.vue')['default']
    ITextFieldAddon: typeof import('./components/CustomVuetify/ITextFieldAddon.vue')['default']
    Modal: typeof import('./components/Modal/Modal.vue')['default']
    ModalConfirm: typeof import('./components/Modal/ModalConfirm.vue')['default']
    ModalDetail: typeof import('./components/Modal/ModalDetail.vue')['default']
    ModalMoveAndCopyTo: typeof import('./components/Modal/ModalMoveAndCopyTo.vue')['default']
    ModalRename: typeof import('./components/Modal/ModalRename.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./components/FileManager/CustomCellTemplate/Share.vue')['default']
    TableFilemanager: typeof import('./components/FileManager/TableFilemanager/TableFilemanager.vue')['default']
    ToolbarFilemanager: typeof import('./components/FileManager/ToolbarFilemanager/ToolbarFilemanager.vue')['default']
  }
}
