/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColumnDateModified: typeof import('./components/FileManager/CustomCellTemplate/ColumnDateModified.vue')['default']
    ColumnGroupActions: typeof import('./components/FileManager/CustomCellTemplate/ColumnGroupActions.vue')['default']
    ColumnLocation: typeof import('./components/FileManager/CustomCellTemplate/ColumnLocation.vue')['default']
    ColumnName: typeof import('./components/FileManager/CustomCellTemplate/ColumnName.vue')['default']
    ColumnOwner: typeof import('./components/FileManager/CustomCellTemplate/ColumnOwner.vue')['default']
    ColumnPermissionFile: typeof import('./components/FileManager/CustomCellTemplate/ColumnPermissionFile.vue')['default']
    ColumnTimeDeleted: typeof import('./components/FileManager/CustomCellTemplate/ColumnTimeDeleted.vue')['default']
    ContextMenu: typeof import('./components/FileManager/ContextMenu/ContextMenu.vue')['default']
    ContextMenuItem: typeof import('./components/FileManager/ContextMenu/ContextMenuItem.vue')['default']
    FileManager: typeof import('./components/FileManager/FileManager.vue')['default']
    FmContextMenu: typeof import('./components/FileManager/ContextMenu/FmContextMenu.vue')['default']
    FmContextMenuItem: typeof import('./components/FileManager/ContextMenu/FmContextMenuItem.vue')['default']
    FmContextMenuItemv2: typeof import('./components/FileManager/ContextMenu/FmContextMenuItemv2.vue')['default']
    FMCreateFolderFile: typeof import('./components/FileManager/Popup/FMCreateFolderFile.vue')['default']
    FMDeleteFolderFile: typeof import('./components/FileManager/Popup/FMDeleteFolderFile.vue')['default']
    FMEmpty: typeof import('./components/FileManager/partial/FMEmpty.vue')['default']
    FMMoveTrashFolderFile: typeof import('./components/FileManager/Popup/FMMoveTrashFolderFile.vue')['default']
    FMRenameFolderFile: typeof import('./components/FileManager/Popup/FMRenameFolderFile.vue')['default']
    GridItem: typeof import('./components/FileManager/GridItem/GridItem.vue')['default']
    IconTag: typeof import('./components/Icons/IconTag.vue')['default']
    Lucide: typeof import('./components/Icons/Lucide.vue')['default']
    Modal: typeof import('./components/Modal/Modal.vue')['default']
    ModalMoveAndCopyTo: typeof import('./components/Modal/ModalMoveAndCopyTo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./components/FileManager/CustomCellTemplate/Share.vue')['default']
    TableFilemanager: typeof import('./components/FileManager/TableFilemanager/TableFilemanager.vue')['default']
    ToolbarFilemanager: typeof import('./components/FileManager/ToolbarFilemanager/ToolbarFilemanager.vue')['default']
  }
}
