/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/manage-storage': RouteRecordInfo<'/manage-storage', '/manage-storage', Record<never, never>, Record<never, never>>,
    '/my-files': RouteRecordInfo<'/my-files', '/my-files', Record<never, never>, Record<never, never>>,
    '/need-access': RouteRecordInfo<'/need-access', '/need-access', Record<never, never>, Record<never, never>>,
    '/not-found': RouteRecordInfo<'/not-found', '/not-found', Record<never, never>, Record<never, never>>,
    '/office': RouteRecordInfo<'/office', '/office', Record<never, never>, Record<never, never>>,
    '/open': RouteRecordInfo<'/open', '/open', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/share-public': RouteRecordInfo<'/share-public', '/share-public', Record<never, never>, Record<never, never>>,
    '/trash': RouteRecordInfo<'/trash', '/trash', Record<never, never>, Record<never, never>>,
  }
}
